version: '3'

services:
   wordpress:
     build: .
     image: wordpress-app:0.0.1
     ports:
       - "8080:8080"
       - "2222:2222"
     restart: always
     environment:
       WORDPRESS_DB_HOST: <mysql_host>:<port>
       WORDPRESS_DB_USER: <mysql_user>
       WORDPRESS_DB_PASSWORD: <mysql_password>
