version: '3'

services:
   wordpress:
     build:
        context: .
        dockerfile: Dockerfile.webapp
     image: wordpress-app:0.0.1
     ports:
       - "80:80"
       - "2222:2222"
     restart: always
     domainname: localhost
     environment:
       WORDPRESS_DB_HOST: <mysql_host>:<port>
       WORDPRESS_DB_USER: <mysql_user>
       WORDPRESS_DB_PASSWORD: <mysql_password>
